#!/usr/bin/env python3
"""YDK unified guard hook — all guard checks in one script."""
import json, sys, threading
from pathlib import Path

# Read stdin (Claude Code pipes tool context as JSON).
# A POSIX-only readiness check on sys.stdin would raise on Windows, so a
# background thread with a join timeout is used instead — it works the
# same way on every platform and still fails open (allows the action) if
# no data shows up within the timeout.
def _read_stdin(timeout=0.5):
    box = {}
    def _reader():
        try:
            box["data"] = sys.stdin.read()
        except Exception:
            box["data"] = ""
    t = threading.Thread(target=_reader, daemon=True)
    t.start()
    t.join(timeout)
    if t.is_alive():
        return None  # No data in time = allow
    return box.get("data", "")

raw = _read_stdin(0.5)
if raw is None:
    sys.exit(0)  # No data = allow

try:
    data = json.loads(raw)
except (json.JSONDecodeError, ValueError):
    sys.exit(0)  # Bad data = fail open

tool_name = data.get("tool_name", "")
tool_input = data.get("tool_input", {})
cwd = data.get("cwd", ".")
file_path = tool_input.get("file_path", "")
command = tool_input.get("command", "")

# Normalize file_path (remove cwd prefix)
if file_path.startswith(cwd):
    file_path = file_path[len(cwd):].lstrip("/")

root = Path(cwd)

# --- GUARD: no-manual-pr and no-direct-push ---
# Stage 01 (brainstorming) has no task ID yet, so 'ydk task done' can't be used
# to PR narratives/component manifests. Allow manual PRs only in that stage.
_stage_file = root / ".ydk" / "state.json"
_stage = "00"
if _stage_file.exists():
    try:
        _stage = json.loads(_stage_file.read_text()).get("stage", "00")
    except Exception:
        pass

if tool_name == "Bash" and ("gh pr create" in command or "gh pr merge" in command) and _stage != "01":
    sys.stderr.write("BLOCKED: Use 'ydk task done' to create PRs — it captures verification proof.\n")
    sys.exit(2)
# git push is allowed — ydk task done needs it internally
# Only gh pr create is blocked (forces proof-based PRs), except in stage 01

# --- GUARD: no-proof-tamper ---
if tool_name in ("Edit", "Write") and ".ydk/proofs/" in file_path and "summary.md" not in file_path:
    sys.stderr.write("BLOCKED: Proof files are generated by 'ydk task done'. Do not edit manually.\n")
    sys.exit(2)

# --- GUARD: no-noqa ---
if tool_name in ("Edit", "Write"):
    new_content = tool_input.get("new_string", "") or tool_input.get("content", "")
    if new_content and not file_path.startswith("tests/"):
        for marker in ("# noqa", "# type: ignore", "# nosec"):
            if marker in new_content:
                sys.stderr.write(f"BLOCKED: '{marker}' not allowed. Fix the violation instead of suppressing it.\n")
                sys.exit(2)

# --- GUARD: no-mock-internals ---
if tool_name in ("Edit", "Write") and file_path.startswith("tests/"):
    new_content = tool_input.get("new_string", "") or tool_input.get("content", "")
    if new_content:
        for pattern in ('@patch("app.', '@patch("src.', "@patch('app.", "@patch('src."):
            if pattern in new_content:
                sys.stderr.write("BLOCKED: Don't mock internal classes. Use fakes and DI overrides.\n")
                sys.exit(2)

# --- GUARD: stage-gate ---
state_file = root / ".ydk" / "state.json"
if state_file.exists() and file_path:
    try:
        state = json.loads(state_file.read_text())
        stage = state.get("stage", "00")

        # Stage 01/02: block source file edits
        if stage in ("01", "02") and file_path.startswith(("src/", "app/", "tests/")):
            if not file_path.startswith(".ydk/"):
                sys.stderr.write(f"BLOCKED: Stage {stage} — cannot edit source files yet.\n")
                sys.exit(2)
    except Exception:
        pass  # State unreadable = allow

sys.exit(0)  # All checks passed — allow
